import {$,el,field,option,panel,table,setStatus} from './common/dom.js';import {loadJSON} from './common/data.js';import {download,downloadJSON} from './common/download.js';import {compareScale,renderPCM,encodeWAV,playScale,frequency,cents} from './core.js';
const app=$('#app');let scale,catalog;
async function main(){catalog=await loadJSON('./data/catalog.json');const scales=catalog.items.filter(i=>i.kind==='scale'),experiments=catalog.items.filter(i=>i.kind==='experiment');const system=el('select',{id:'system'},[...new Set(scales.map(s=>s.system))].map(s=>option(s,s.replaceAll('-',' '))));const root=el('select',{id:'root-note'},['C4','D4','E4','F4','G4','A4'].map(n=>option(n,n)));const experiment=el('select',{id:'experiment'},experiments.map(e=>option(e.id,e.title)));
 async function change(){try{const item=scales.find(s=>s.system===system.value&&s.root_note===root.value);scale=await loadJSON('./'+item.path);render();setStatus('Tuning model loaded.');}catch(e){setStatus(e.message,'error');}}
 system.addEventListener('change',change);root.addEventListener('change',change);experiment.addEventListener('change',showExperiment);
 app.append(el('div',{class:'layout'},[el('aside',{},[panel('Tuning explorer',[field('Mathematical model',system),field('Root note',root),field('Interval experiment',experiment),el('p',{class:'notice',text:'Historical inspiration with modern comparison models. These examples do not reconstruct a particular ancient performance.'})])]),el('div',{id:'content'})]));await change();await showExperiment();
 async function showExperiment(){const item=experiments.find(e=>e.id===experiment.value);const e=await loadJSON('./'+item.path);const box=$('#experiment-detail');if(box)box.replaceChildren(el('p',{text:e.title}),table(['Ratio','Frequency','Cents'],[[e.ratio,frequency(e.root_hz,e.ratio).toFixed(3)+' Hz',cents(e.ratio).toFixed(3)]]));}
 window.showExperiment=showExperiment;
}
function render(){const content=$('#content');content.replaceChildren();const rows=compareScale(scale);const plot=el('canvas',{id:'pitch-plot',class:'plot',width:900,height:180,'aria-label':'Pitch deviation from equal temperament'});
 const actions=el('div',{class:'actions'},[el('button',{id:'play-scale',text:'Play synthesised scale',onclick:async()=>{try{await playScale(rows.map(r=>r.frequency_hz));setStatus('Playing quiet sine tones.');}catch(e){setStatus(e.message,'error');}}}),el('button',{id:'export-wav',class:'secondary',text:'Download WAV',onclick:()=>download(encodeWAV(renderPCM(rows.map(r=>r.frequency_hz))),'tuning-scale.wav','audio/wav')}),el('button',{id:'export-json',class:'secondary',text:'Export pitch table',onclick:()=>downloadJSON({id:'SYN-TUNING-001',project_id:'greek-music-wolfram',is_synthetic:true,created_at:new Date().toISOString(),payload:{scale,rows}},'tuning-comparison.json')})]);
 content.append(panel(scale.title,[el('p',{class:'muted',text:'Root: '+scale.root_hz.toFixed(3)+' Hz · model ratios compared with twelve-tone equal temperament'}),plot,actions,el('div',{class:'scroll'},[table(['Degree','Ratio','Model Hz','Equal Hz','Difference'],rows.map(r=>[r.degree,r.ratio,r.frequency_hz.toFixed(3),r.equal_hz.toFixed(3),r.cents_difference.toFixed(3)+' cents']))])]),panel('Interval laboratory',[el('div',{id:'experiment-detail'})]));
 const ctx=plot.getContext('2d');ctx.strokeStyle='#afc5bc';ctx.beginPath();ctx.moveTo(40,90);ctx.lineTo(860,90);ctx.stroke();rows.forEach((r,i)=>{const x=50+i*(800/Math.max(1,rows.length-1)),height=Math.max(-65,Math.min(65,r.cents_difference*3));ctx.fillStyle='#087d77';ctx.fillRect(x-12,Math.min(90,90-height),24,Math.max(2,Math.abs(height)));ctx.fillStyle='#183542';ctx.font='12px system-ui';ctx.fillText(String(r.degree),x-4,165);});if(window.showExperiment)window.showExperiment();
}
main().catch(e=>setStatus(e.message,'error'));
